In [ ]:
import pandas as pd
import numpy as np

arr = np.array([1,2,3,4])
pand_arr = pd.Series(arr, index = ['ab','cd','ef','gh'])
print(pand_arr)

pand_arr_updated = pand_arr + 3
print(pand_arr_updated)

ab    1
cd    2
ef    3
gh    4
dtype: int64
ab    4
cd    5
ef    6
gh    7
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

arr = np.array([1,2,3,4])
grade = np.array(['A','B','C','D'])
pand_arr = pd.DataFrame({'student': arr ,'Grades': grade })
pand_arr

   student Grades
0        1      A
1        2      B
2        3      C
3        4      D

In [26]:
import pandas as pd

df = pd.DataFrame({
    "user_id": [1,2,3,4,5,6],
    "age": [25, 34, None, 45, 23, 36],
    "department": ["Sales", "Tech", "Tech", "HR", "Sales", "Tech"],
    "salary": [50000, 80000, 75000, None, 52000, 90000],
    "join_date": ["2020-01-15", "2019-03-10", "2021-06-01", "2018-07-23", "2022-02-20", "2020-11-11"],
    "left_company": [0,1,0,1,0,1]
})
df.loc[df["age" ] >30, 'user_id']
df.loc[(df["salary"] > 6000) & (df['department'] == "Tech"), "user_id" ]
df.loc[ (df["age"]>30) | (df["salary"] >100000)  , "user_id"]

1    2
3    4
5    6
Name: user_id, dtype: int64

In [49]:
import pandas as pd

df = pd.DataFrame({
    "user_id": [1,2,3,4,5,6],
    "age": [25, 34, None, 45, 23, 36],
    "department": ["Sales", "Tech", "Tech", "HR", "Sales", "Tech"],
    "salary": [50000, 80000, 75000, None, 52000, 90000],
    "join_date": ["2020-01-15", "2019-03-10", "2021-06-01", "2018-07-23", "2022-02-20", "2020-11-11"],
    "left_company": [0,1,0,1,0,1]})

df_new = df.isna()
df_new.loc[df_new ['age'] == 'true']
df.groupby('department') ["salary"].mean().max()

81666.66666666667

In [58]:
import pandas as pd

users = pd.DataFrame({
    "user_id": [1, 2, 3, 4],
    "department": ["IT", "HR", "IT", "Finance"],
    "salary": [90000, 60000, 110000, 75000]
})

performance = pd.DataFrame({
    "user_id": [1, 2, 3, 5],
    "performance_score": [8, 7, 9, 6]
})
df = pd.merge (users,performance , on = "user_id", how = 'outer'  )
df
df.loc[df['salary'].isna(), "user_id"]

4    5
Name: user_id, dtype: int64